---
- name: Install QEMU agent for proxmox control
  hosts: students
  become: true
  serial: 2

  tasks:
    - name: Install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
        update_cache: yes
      when: ansible_distribution in ["Ubuntu", "Debian", "Kali"]

    - name: Ensure qemu-guest-agent is running and enabled
      systemd:
        name: qemu-guest-agent
        state: started
        enabled: true
      register: qemu_guest_agent_status
      when: ansible_distribution in ["Ubuntu", "Debian", "Kali"]

    - name: Debug qemu-guest-agent status
      debug:
        msg: "QEMU Guest Agent is {{ qemu_guest_agent_status.state }}"
      when: ansible_distribution in ["Ubuntu", "Debian", "Kali"]