- import_playbook: reboot.yml

- name: 60
  hosts: all
  gather_facts: false
  tasks:
    - name: Pause for 60 seconds
      ansible.builtin.pause:
        seconds: 60

- import_playbook: install_qemu.yml
- import_playbook: reboot.yml
